/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SomeComponent {
    }
}
declare global {
    interface HTMLSomeComponentElement extends Components.SomeComponent, HTMLStencilElement {
    }
    var HTMLSomeComponentElement: {
        prototype: HTMLSomeComponentElement;
        new (): HTMLSomeComponentElement;
    };
    interface HTMLElementTagNameMap {
        "some-component": HTMLSomeComponentElement;
    }
}
declare namespace LocalJSX {
    interface SomeComponent {
    }
    interface IntrinsicElements {
        "some-component": SomeComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "some-component": LocalJSX.SomeComponent & JSXBase.HTMLAttributes<HTMLSomeComponentElement>;
        }
    }
}
